class Demo:
    EXPECTED_NAME_UPLOAD_FILE = "picture.png"
    EXPECTED_NAME_DOWNLOAD_FILE = "sampleFile.jpeg"


class Downloads:
    EXPECTED_NAMES = [
        "LambdaTest.txt",
        "eleventh_session.pptx",
        "sample-zip-file.zip",
        "WhatsApp Installer.exe",
        "chromedriver.exe",
        "nikki.txt",
        "seleniumImage.png",
        "text-file-1.txt",
        "document.pdf",
        "random_data.txt",
        "Eighth_session.pptx",
        "10mb.pdf",
        "bb.txt",
        "image (10).png",
        "practise.png",
        "example.pdf",
        "some-file.txt",
        "91231.jpg",
        "emptyTest.rtf",
        "Caption.jpg",
        "test.txt",
        "text-file-2.txt",
        "Detection (vlc).exe",
        "Faizan SQA Resume.pdf",
        "fifth_session.pptx",
        "Nilesh_Kasane_Cover_Letter.PDF",
        "9a92c55da0ef14b14dfe.jpg",
        "class1_19Apr2025.png",
        "image (4).jpeg",
        "NH.jpg",
        "text.txt",
        "First_session.pptx",
        "newfile.pdf",
        "zip.txt",
        "Blank Document.pages",
        "gpay.PNG",
        "yellow-gift-with-golden-ribbon-icon-sign-symbol-3d-background-illustration_56104-2422.avif",
        "local.py",
        "Jpeg_with_exif.jpeg",
        "example.json",
        "TestNew.txt",
        "sample.txt",
        "file-sample_100kB.doc",
        "CHARAN.KARNA.docx",
        "zero_bytes_file.txt",
        "German_A1_Basics_Study_Sheet.pdf",
        "Entity Issue.png",
        "तू हार नहीं सकता.png",
        "test_file.txt",
        "txtfile.txt"
    ]
